@StockAPI_HostAddress = http://localhost:3000/api/v1

### Get all products
GET {{StockAPI_HostAddress}}/products
Accept: application/json

### Get a product by their id
GET {{StockAPI_HostAddress}}/products/20
Accept: application/json

### Example post request for a new product
POST {{StockAPI_HostAddress}}/products
Content-Type: application/json
Accept: application/json
{
  "name": "Wireless Mouse",
  "category": 1,
  "stock": 70
}

### Example post request for adding stock to a product based on id
POST {{StockAPI_HostAddress}}/products/1/stock/add
Content-Type: application/json
Accept: application/json
{
  "amount": 10
}

### Example post request for removing stock to a product based on id
POST {{StockAPI_HostAddress}}/products/10/stock/remove
Content-Type: application/json
Accept: application/json
{
  "amount": 10
}

### Example post request for updating a products information based on id
PUT {{StockAPI_HostAddress}}/products/1
Content-Type: application/json
Accept: application/json
{
  "name": "HOP HOP",
  "price": 85,
  "stock": 60,
  "category": 5
}

### Example delete request for deleting a product based on id
DELETE {{StockAPI_HostAddress}}/products/27
Accept: application/json